### ISSUE TITLE
/dattz

### ISSUE THREAD

**Issue by laniromee** [HeadacheMan/ritsuko-bot#1]
comando que aleatoriamente manda um dos xingamentos ao dattz do banco de dados. sugestões:

Estragão.
Atrasão.
É gay.
VAI DESENHAR ABNOR
Otakaço.
NERD
Virjão.
Tony Stark morre em Avengers 2.

**Comment by HeadacheMan** [comment]
Pode ter um lance também pra galera ir mandando uns xingamentos novos e adicionar ao comando, que tal?

**Comment by Kleptos** [comment]
Ai é loco

**Comment by laniromee** [comment]
mas aí sem filtro? porque vai que alguem chega e bota pra adicionar um poema do leminski, por exemplo. fodeu o banco

**Comment by Kleptos** [comment]
Acho que deve dar pra limitar os usuários. Ai coloca todo mundo menos o Dattz.

**Comment by HeadacheMan** [comment]
Sim, dá pra limitar pra que só o datzz não possa mandar xingamentos para serem adicionados.

**Comment by laniromee** [comment]
aí é bom demais

**Comment by HeadacheMan** [comment]
Vou por isso na milestone pra depois do roll
