### ISSUE TITLE
/ajuda

### ISSUE THREAD

**Issue by popocake** [HeadacheMan/ritsuko-bot#2]
Poderíamos ter um comando /ajuda (ou algo do tipo, pode ser /responda também, sei lá), para que a RitsukoBot nos desse uma resposta a algum dilema que precisa ser resolvido rapidamente. A ideia é que ela responda aleatoriamente dentro um rol de respostas possíveis que ela tenha pré-programado. As opções de resposta disponíveis são essas:

Sim;
Não;
Talvez;
Tente de novo mais tarde;
Mas tu é burro?;
Vai em frente;
....de novo?;
Vou pensar no assunto;
Só DEUS sabe;
Pode crer;
...;
Definitivamente;
Calaboca;
ZIUZIUZIU;
Bakyun!;
Pode ser né;
Complicado;
Como você é merda

**Comment by laniromee** [comment]
eu sou contra esses "talvez"es e "tente depois mais tarde"s e "vou pensar"es. nossa ritsukobot tem que ter respostas definitivas, ainda que reticentes, não podem ser respostas redundantes que só te farão perguntar de novo imediatamente. e algumas como "vai em frente" estão num formato não universal, não casarão com todas as perguntas... minha proposta seria:

ÓBVIO, NÉ
Claro!
Sim.
P-pode ser...
Só DEUS sabe.
complicado
Nnnnnão?
Não.
Tá maluco?
EVIDENTE QUE NÃO, PASPALHO

**Comment by laniromee** [comment]
divisão de respostas, respeitar as grafias:

------- POSITIVAS (45%) ---------
ÓBVIO, NÉ
Claro!
Sim.
P-pode ser...
pode crer
Definitivamente.
Pode ser né

-------- NEUTRAS (10%) --------------
:l
complicado
Só DEUS sabe.
PASSO

--------- NEGATIVAS (45%) ------------
putz, nem.
Nnnnnão?
Não.
cara vamos dizer que não
T-tá maluco?
HAHAHAHAHAnão
EVIDENTE QUE NÃO, BOBÃO

**Comment by laniromee** [comment]
não esquecer de mudar o comando pra /ritsuko

**Comment by HeadacheMan** [comment]
Refatorado para comando /ritsuko e feito a distribuição das respostas de acordo com as porcentagens escolhidas.
